version: '3.4'

services:
  ztp.api:
    build:
      context: .
      dockerfile: Ztp.Api/Dockerfile
    environment:
      - DOCKER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5077:80"
    depends_on:
      - ztp.database
      - rabbitmq

  ztp.webjobs.domain:
    build:
      context: .
      dockerfile: Ztp.WebJobs.Domain/Dockerfile
    depends_on:
      - rabbitmq
  
  ztp.webjobs.projections:
    build:
      context: .
      dockerfile: Ztp.WebJobs.Projections/Dockerfile
    depends_on:
      - rabbitmq

  ztp.database:
    image: postgres:13
    environment:
      POSTGRES_DB: ztp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
